name: doxygen

on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ main ]

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install doxygen --yes

      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Upload Documentation
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/html/